Allow passing desired name while creating account.
XRPLF/xrpl-hooks-ide pull request #231
Opened 2022-07-01 09:04 UTC by muzam1l

Fixes #198

2022-07-01 09:25 UTC, valstu requested changes
What do you think, would it make sense to add name field to import account as well? 🤔

2022-07-01 09:25 UTC, valstu requested changes
What do you think, would it make sense to add name field to import account as well? 🤔

2022-07-01 10:39 UTC, vbar commented
> What do you think, would it make sense to add name field to import account as well? thinking

Yes, I think it makes sense especially for import...

2022-07-01 10:46 UTC, muzam1l commented on components/Accounts.tsx
> +      addFaucetAccount(name, true);
Yes!

2022-07-01 13:10 UTC, vbar requested changes
It's very nonobvious to me that I don't _have_ to fill in the name - I think the dialog should include a comment (or help popup, or something) to that effect...

2022-07-08 12:46 UTC, muzam1l commented
Okay to merge?

2022-07-08 13:01 UTC, vbar commented
> Okay to merge?

Ah, that's why it isn't on hooks-builder.xrpl.org - it hadn't been merged yet... I'd say yes, but on Monday... :-)

2022-07-11 08:59 UTC, merged