Update readme link
XRPLF/xrpl-hooks-ide pull request #304
Opened 2023-06-06 12:31 UTC by dangell7

I don't think we should be linking directly to a specific version. Readme will automatically show the most recent version.

We are on version 3 now.

2023-06-06 12:51 UTC, vbar requested changes
I agree in general (the links are AFAIK older than dynamic versioning), but the changed links shouldn't contain double slashes...

2023-06-06 12:54 UTC, dangell7 commented
> I agree in general (the links are AFAIK older than dynamic versioning), but the changed links shouldn't contain double slashes...

No they should not. :)

2023-06-06 13:02 UTC, vbar approved these changes

2023-06-11 06:34 UTC, merged

2023-06-11 06:34 UTC, WietseWind commented
Thanks @dangell7, merged :)